# Generated by Django 4.2.7 on 2025-09-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_profile_city_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonstage',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hackathonstage',
            name='start_date',
            field=models.DateField(),
        ),
    ]
